export const ActionTypes = {
  ALL_PRODUCTS: "ALL_PRODUCTS",
  SELECTED_PRODUCT: "SELECTED_PRODUCT",

  // cartActions
  ADD_TO_CART: "ADD_TO_CART",
  GET_LOGGED_CART: "GET_LOGGED_CART",
  DELETE_ITEM: "DELETE_ITEM",
  UPDATE_QTY: "UPDATE_QTY",
  CLEAR_ALL_CART: "CLEAR_ALL_CART",

  // wishList
  ADD_TO_LIST: "ADD_TO_LIST",
  GET_LOGGED_LIST: "GET_LOGGED_LIST",
  DELETE_ITEM_LIST: "DELETE_ITEM_LIST",

  // filters
  SORT_BY_PRICE:"SORT_BY_PRICE"
};
